# Generated by Django 5.1.5 on 2025-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('res_street_number', models.IntegerField()),
                ('res_street_name', models.TextField()),
                ('res_apartment_number', models.TextField()),
                ('res_zip_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('dor', models.DateField()),
                ('party_affiliation', models.CharField(max_length=6)),
                ('precinct_number', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
