# Generated by Django 5.1.5 on 2025-02-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
