# Generated by Django 5.1.5 on 2025-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="address",
            new_name="restaurant_city",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_state",
            field=models.TextField(default="KY"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_street_name",
            field=models.TextField(default="11"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_street_number",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_zip_code",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
