# Generated by Django 5.1.5 on 2025-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_address_restaurant_restaurant_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.TextField(
                choices=[
                    ("american", "American"),
                    ("chinese", "Chinese"),
                    ("italian", "Italian"),
                    ("japanese", "Japanese"),
                    ("mexican", "Mexican"),
                    ("indian", "Indian"),
                    ("thai", "Thai"),
                    ("french", "French"),
                    ("greek", "Greek"),
                    ("mediterranean", "Mediterranean"),
                ]
            ),
        ),
    ]
