# Generated by Django 5.1.5 on 2025-04-15 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_restaurant_cuisine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="project.restaurant",
            ),
        ),
    ]
