# Generated by Django 5.1.5 on 2025-04-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
