# Generated by Django 5.1.5 on 2025-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField()),
                ('last', models.TextField()),
                ('city', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('profile_image_url', models.URLField(blank=True)),
            ],
        ),
    ]
