# Generated by Django 5.1.5 on 2025-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_alter_statusmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
